name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Read value from repository variables
      env:
        API_KEY_ENV: ${{ vars.API_KEY }}
      run: |
        echo "API_KEY value is $API_KEY_ENV"
    - name: Write value to Properties-file
      uses: christian-draeger/write-properties@1.1.0
      with:
        path: 'api.properties'
        property: 'apiKey'
        value: '${{ vars.API_KEY }}'
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run tests with Gradle
      run: ./gradlew test
    - name: Run lint with Gradle
      run: ./gradlew detekt lintKotlin lint
